const products = [
    {
        _id: '1',
        name: 'OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM, 128GB Storage)',
        image: 'https://m.media-amazon.com/images/I/71AvQd3VzqL._SX679_.jpg',
        images: [
            'https://m.media-amazon.com/images/I/71AvQd3VzqL._SX679_.jpg',
            'https://m.media-amazon.com/images/I/61kGS9bJjpL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/61wLFaBkPiL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/614Yr-udTqL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/51SFuLH8rFL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/5184L3zMSmL._SL1500_.jpg',
        ],
        description: [
            'Camera: 64MP Main Camera with EIS; 2MP Depth Lens and 2MP Macro Lens; Front (Selfie) Camera: 16MP Sony IMX471 ',
            'Camera Features: AI scene enhancement, Dual-View Video, HDR, Night Portrait, Panorama Mode, Retouch Filters, 1080p video at 30 fps, SLO-MO: 720p video at 120 fps, TIME-LAPSE: 1080p video at 30 fps, Video editor, Face unlock, Screen flash, HDR, NIGHT, PORTRAIT, TIME-LAPSE, Retouch, Filters', 
            'Display: 6.59 Inches; 120 Hz Refresh Rate; Support sRGB, Display P3; Resolution: 2412 x 1080 pixels 402ppi; Aspect Ratio: 20:9', 
            'Display Features: Dark mode', 
            'Operating System: Oxygen OS based on Android 12', 
            'Processor: Qualcomm Snapdragon 695 5G', 
            'Battery & Charging: 5000 mAh with 33W SuperVOOC', 
            'Alexa Hands-Free capable: Download the Alexa app to use Alexa hands-free. Play music, make calls, hear news, open apps, navigate, and more, all using just your voice, while on-the-go.', 
            'Cellular technology: 5g, 4g lte', 
            'operating system:oxygenos, display_type:lcd, form_factor:smartphone'],
        category: 'Electronics',
        price: 19999,
        rating: 4.2,
        numReviews: 3,
    },
    {
        _id: '2',
        name: 'Mi 11X 5G (Cosmic Black 8GB RAM 128GB ROM) | SD 870 | DisplayMate A+ rated E4 AMOLED | Extra offers on exchange | Upto 18 Months No Cost EMI',
        image: 'https://m.media-amazon.com/images/I/71VQXjN6R7S._SL1500_.jpg',
        images: [
            'https://m.media-amazon.com/images/I/71VQXjN6R7S._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/41QNmEyo+bS._SL1280_.jpg',
            'https://m.media-amazon.com/images/I/81oBh-6d6nL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/61MvBq4OJoS._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/31HTh8-LfWS._SL1280_.jpg',
            'https://m.media-amazon.com/images/I/41OgQ6N32XS._SL1280_.jpg',
            'https://m.media-amazon.com/images/I/41KH2nHYUWS._SL1280_.jpg',
        ],
        description: ['Processor: Qualcomm Snapdragon 870 5G with Kryo 585 Octa-core; 7nm process; Up to 3.2GHz clock speed; Liquidcool technology', 
        'Camera: 48 MP Triple Rear camera with 8MP Ultra-wide and 5MP Super macro | 20 MP Front camera', 
        'Display: 120Hz high refresh rate FHD+ (1080x2400) AMOLED Dot display; 16.9 centimeters (6.67 inch); 2.76mm ultra tiny punch hole; HDR 10+ support; 360Hz touch sampling, MEMC technology', 
        'Battery: 4520 mAH large battery with 33W fast charger in-box and Type-C connectivity', 
        'Hands-Free access to Alexa: Alexa on your phone lets you make phone calls, open apps, control smart home devices, access the library of Alexa skills, and more using just your voice while on-the-go. Download the Alexa app and complete hands-free setup to get started. Just ask - and Alexa will respond instantly', 
        '5G Bands SA: N77 | N78; NSA: N77 | N78'
            ],
        category: 'Electronics',
        price: 29999,
        rating: 4,
        numReviews: 2,
    },
    {
        _id: '3',
        name: 'Apple iPhone 13 (128GB) - Blue',
        image: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        images: [
            'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/61CAYVr34QL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/81junVbiuyL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/81edi2EvglL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/81-hHbjQGSL._SL1500_.jpg',
            'https://m.media-amazon.com/images/I/61wIVtrz54L._SL1500_.jpg',
        ],
        description: ['15 cm (6.1-inch) Super Retina XDR display', 
        'Cinematic mode adds shallow depth of field and shifts focus automatically in your videos', 
        'Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording', 
        '12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording', 
        'A15 Bionic chip for lightning-fast performance', 
        'Up to 19 hours of video playback', 
        ' Durable design with Ceramic Shield\n Industry-leading IP68 water resistance', 
        'iOS 15 packs new features to do more with iPhone than ever before', 
        'Supports MagSafe accessories for easy attachment and faster wireless charging'],
        category: 'Electronics',
        price: 69900,
        rating: 5,
        numReviews: 2,
    },
    {
        _id: '4',
        name: 'Dell XPS 13 Plus Laptop, Intel i7-1260P, 16GB, 1TB SSD, Win 11 + MSO\'21, 13.4" (34.036Cms) UHD+ AR 500 nits Touch, Backlit KB, 1.24Kgs (D560075WIN9S)',
        image: 'https://m.media-amazon.com/images/I/61rvR2b3flL._SL1080_.jpg',
        images: [
            'https://m.media-amazon.com/images/I/61rvR2b3flL._SL1080_.jpg',
            'https://m.media-amazon.com/images/I/61fMp4UcwyL._SL1080_.jpg',
            'https://m.media-amazon.com/images/I/51d2bQDEzcL._SL1080_.jpg',
            'https://m.media-amazon.com/images/I/51NHKUXMQdL._SL1080_.jpg',
            'https://m.media-amazon.com/images/I/61NkZfY+lqL._SL1080_.jpg',
            'https://m.media-amazon.com/images/I/51wfuHkMSYL._SL1080_.jpg',
            'https://m.media-amazon.com/images/I/61gExCzWeCL._SL1500_.jpg'
            
        ],
        description: [
            'Processor: Intel i7-1260P (3.40 GHz up to 4.70 GHz)', 'RAM & Storage: 16GB LPDDR5 & 1TB SSD', 
            'Display & Keyboard: 13.4" UHD+ AR Infinity Edge 500 nits Touch & Backlit Keyboard', 
            'Software: Win 11 + Office H&S 2021', 
            'Ports: 2x Thunderbolt 4 (USB Type C ) with DisplayPort and Power Delivery, 1 USB C to USB A v3.0 adapter ships standard'],
        category: 'Electronics',
        price: 179990,
        rating: 5,
        numReviews: 2,
    },
    {
        _id: '',
        name: '',
        image: '',
        description: '',
        category: '',
        price: '',
        rating: '5',
        numReviews: '2',
    },
]; 

export default products

